In [1]:
pip install geopandas

Requirement already satisfied: geopandas in c:\users\aican\anaconda3\lib\site-packages (1.0.1)
Requirement already satisfied: numpy>=1.22 in c:\users\aican\anaconda3\lib\site-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\aican\anaconda3\lib\site-packages (from geopandas) (0.10.0)
Requirement already satisfied: packaging in c:\users\aican\anaconda3\lib\site-packages (from geopandas) (24.1)
Requirement already satisfied: pandas>=1.4.0 in c:\users\aican\anaconda3\lib\site-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.3.0 in c:\users\aican\anaconda3\lib\site-packages (from geopandas) (3.7.1)
Requirement already satisfied: shapely>=2.0.0 in c:\users\aican\anaconda3\lib\site-packages (from geopandas) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aican\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aican\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aican\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2023.3)
Requirement already satisfied: certifi in c:\users\aican\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.4.26)
Requirement already satisfied: six>=1.5 in c:\users\aican\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# Load Berlin districts GeoJSON
districts = gpd.read_file(r"C:\Users\aican\2025-Ironhack\GitHub\Unit8-2025-CW-23\Airbnb-Prices-in-European-Cities\bezirksgrenzen.geojson")

In [17]:
# Load Airbnb listings (CSV with latitude and longitude columns)
df_combined = pd.read_excel(r"C:\Users\aican\2025-Ironhack\GitHub\Unit8-2025-CW-23\Airbnb-Prices-in-European-Cities\df_combined.xlsx")

In [18]:
# Create Point geometries from lat/lon
geometry = [Point(xy) for xy in zip(df_combined['lng'], airbnb_df['lat'])]

# Create GeoDataFrame
airbnb_gdf = gpd.GeoDataFrame(df_combined, geometry=geometry, crs="EPSG:4326")

In [21]:
# Reproject Airbnb points to match districts' CRS
airbnb_gdf = airbnb_gdf.to_crs(districts.crs)

In [23]:
# Perform the spatial join: which district polygon contains each Airbnb point
joined = gpd.sjoin(airbnb_gdf, districts, how="left", predicate="within")

In [31]:
joined.head(5)

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,weekends,city,geometry,index_right,gml_id,Gemeinde_name,Gemeinde_schluessel,Land_name,Land_schluessel,Schluessel_gesamt
0,0,194.033698,Private room,0,1,2,0,1,0,10,...,0,Amsterdam,POINT (4.90569 52.41772),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,344.245776,Private room,0,1,4,0,0,0,8,...,0,Amsterdam,POINT (4.90005 52.37432),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,264.101422,Private room,0,1,2,0,0,1,9,...,0,Amsterdam,POINT (4.97512 52.36103),NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,433.529398,Private room,0,1,4,0,0,1,9,...,0,Amsterdam,POINT (4.89417 52.37663),NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,485.552926,Private room,0,1,2,1,0,0,10,...,0,Amsterdam,POINT (4.90051 52.37508),NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# Now each row in 'joined' has all columns from airbnb + matched district
# For example, if district name is stored in column 'name' in GeoJSON:
joined[['lat', 'lng', 'Gemeinde_name']]  # replace 'name' with correct column

# Save to CSV if needed
joined.to_csv("airbnb_with_districts.csv", index=False)

In [35]:
# Show unique district names
unique_districts = joined["Gemeinde_name"].unique()
print(unique_districts)

[nan 'Neukölln' 'Friedrichshain-Kreuzberg' 'Pankow' 'Lichtenberg'
 'Charlottenburg-Wilmersdorf' 'Treptow-Köpenick' 'Steglitz-Zehlendorf'
 'Mitte' 'Tempelhof-Schöneberg' 'Spandau' 'Marzahn-Hellersdorf'
 'Reinickendorf']

In [39]:
joined.columns

Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat', 'weekends', 'city', 'geometry',
       'index_right', 'gml_id', 'Gemeinde_name', 'Gemeinde_schluessel',
       'Land_name', 'Land_schluessel', 'Schluessel_gesamt'],
      dtype='object')

In [43]:
joined["A"] = "A"

In [45]:
joined.columns

Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat', 'weekends', 'city', 'geometry',
       'index_right', 'gml_id', 'Gemeinde_name', 'Gemeinde_schluessel',
       'Land_name', 'Land_schluessel', 'Schluessel_gesamt', 'A'],
      dtype='object')

In [47]:
joined

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,city,geometry,index_right,gml_id,Gemeinde_name,Gemeinde_schluessel,Land_name,Land_schluessel,Schluessel_gesamt,A
0,0,194.033698,Private room,0,1,2,0,1,0,10,...,Amsterdam,POINT (4.90569 52.41772),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
1,1,344.245776,Private room,0,1,4,0,0,0,8,...,Amsterdam,POINT (4.90005 52.37432),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,2,264.101422,Private room,0,1,2,0,0,1,9,...,Amsterdam,POINT (4.97512 52.36103),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
3,3,433.529398,Private room,0,1,4,0,0,1,9,...,Amsterdam,POINT (4.89417 52.37663),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
4,4,485.552926,Private room,0,1,2,1,0,0,10,...,Amsterdam,POINT (4.90051 52.37508),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48976,51696,359.021107,Private room,0,1,5,0,0,1,10,...,Vienna,POINT (16.36758 48.21567),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
48977,51700,115.933899,Private room,0,1,4,0,1,0,9,...,Vienna,POINT (16.3397 48.19325),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
48978,51703,304.793960,Entire home/apt,0,0,2,0,0,0,8,...,Vienna,POINT (16.3807 48.20296),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
48979,51705,301.054157,Private room,0,1,2,0,0,0,10,...,Vienna,POINT (16.341 48.192),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
48980,51706,133.230489,Private room,0,1,4,1,1,0,10,...,Vienna,POINT (16.39066 48.20811),NaN,NaN,NaN,NaN,NaN,NaN,NaN,A

In [51]:
joined.to_excel("airbnb-berlin-with-districts.xlsx", index=False)

In [53]:
# Add a new column called "joined" with the value "A" for every row
districts["joined"] = "A"

In [55]:
districts

,gml_id,Gemeinde_name,Gemeinde_schluessel,Land_name,Land_schluessel,Schluessel_gesamt,geometry,joined
0,s_wfs_alkis_bezirk.F176__1,Reinickendorf,012,Berlin,11,11000012,"MULTIPOLYGON (((13.32074 52.6266, 13.32045 52....",A
1,s_wfs_alkis_bezirk.F176__2,Charlottenburg-Wilmersdorf,004,Berlin,11,11000004,"MULTIPOLYGON (((13.32111 52.52446, 13.32103 52...",A
2,s_wfs_alkis_bezirk.F176__3,Treptow-Köpenick,009,Berlin,11,11000009,"MULTIPOLYGON (((13.57925 52.39083, 13.57958 52...",A
3,s_wfs_alkis_bezirk.F176__4,Pankow,003,Berlin,11,11000003,"MULTIPOLYGON (((13.50481 52.6196, 13.50467 52....",A
4,s_wfs_alkis_bezirk.F176__5,Neukölln,008,Berlin,11,11000008,"MULTIPOLYGON (((13.45832 52.48569, 13.45823 52...",A
5,s_wfs_alkis_bezirk.F176__6,Lichtenberg,011,Berlin,11,11000011,"MULTIPOLYGON (((13.52316 52.47424, 13.52367 52...",A
6,s_wfs_alkis_bezirk.F176__7,Marzahn-Hellersdorf,010,Berlin,11,11000010,"MULTIPOLYGON (((13.61317 52.47213, 13.61329 52...",A
7,s_wfs_alkis_bezirk.F176__8,Spandau,005,Berlin,11,11000005,"MULTIPOLYGON (((13.23119 52.56124, 13.23092 52...",A
8,s_wfs_alkis_bezirk.F176__9,Steglitz-Zehlendorf,006,Berlin,11,11000006,"MULTIPOLYGON (((13.31952 52.46699, 13.3191 52....",A
9,s_wfs_alkis_bezirk.F176__10,Mitte,001,Berlin,11,11000001,"MULTIPOLYGON (((13.37721 52.56091, 13.37715 52...",A
10,s_wfs_alkis_bezirk.F176__11,Friedrichshain-Kreuzberg,002,Berlin,11,11000002,"MULTIPOLYGON (((13.45529 52.52127, 13.45542 52...",A
11,s_wfs_alkis_bezirk.F176__12,Tempelhof-Schöneberg,007,Berlin,11,11000007,"MULTIPOLYGON (((13.38759 52.38677, 13.38761 52...",A

In [57]:
districts = districts.rename(columns={"joined": "A"})

In [59]:
districts

,gml_id,Gemeinde_name,Gemeinde_schluessel,Land_name,Land_schluessel,Schluessel_gesamt,geometry,A
0,s_wfs_alkis_bezirk.F176__1,Reinickendorf,012,Berlin,11,11000012,"MULTIPOLYGON (((13.32074 52.6266, 13.32045 52....",A
1,s_wfs_alkis_bezirk.F176__2,Charlottenburg-Wilmersdorf,004,Berlin,11,11000004,"MULTIPOLYGON (((13.32111 52.52446, 13.32103 52...",A
2,s_wfs_alkis_bezirk.F176__3,Treptow-Köpenick,009,Berlin,11,11000009,"MULTIPOLYGON (((13.57925 52.39083, 13.57958 52...",A
3,s_wfs_alkis_bezirk.F176__4,Pankow,003,Berlin,11,11000003,"MULTIPOLYGON (((13.50481 52.6196, 13.50467 52....",A
4,s_wfs_alkis_bezirk.F176__5,Neukölln,008,Berlin,11,11000008,"MULTIPOLYGON (((13.45832 52.48569, 13.45823 52...",A
5,s_wfs_alkis_bezirk.F176__6,Lichtenberg,011,Berlin,11,11000011,"MULTIPOLYGON (((13.52316 52.47424, 13.52367 52...",A
6,s_wfs_alkis_bezirk.F176__7,Marzahn-Hellersdorf,010,Berlin,11,11000010,"MULTIPOLYGON (((13.61317 52.47213, 13.61329 52...",A
7,s_wfs_alkis_bezirk.F176__8,Spandau,005,Berlin,11,11000005,"MULTIPOLYGON (((13.23119 52.56124, 13.23092 52...",A
8,s_wfs_alkis_bezirk.F176__9,Steglitz-Zehlendorf,006,Berlin,11,11000006,"MULTIPOLYGON (((13.31952 52.46699, 13.3191 52....",A
9,s_wfs_alkis_bezirk.F176__10,Mitte,001,Berlin,11,11000001,"MULTIPOLYGON (((13.37721 52.56091, 13.37715 52...",A
10,s_wfs_alkis_bezirk.F176__11,Friedrichshain-Kreuzberg,002,Berlin,11,11000002,"MULTIPOLYGON (((13.45529 52.52127, 13.45542 52...",A
11,s_wfs_alkis_bezirk.F176__12,Tempelhof-Schöneberg,007,Berlin,11,11000007,"MULTIPOLYGON (((13.38759 52.38677, 13.38761 52...",A

In [61]:
# Save the updated GeoJSON file
districts.to_file("updated_bezirksgrenzen.geojson", driver="GeoJSON")